sudo: required

services:
  - docker

language: node_js

node_js:
  - "6.9"

cache:
  directories:
    node_modules

script: travis/ci.sh

before_deploy:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: CatalystCode/featureService
      tags: true
